export default [
  { name: "Castle-3", rarity: 1, type: 'guard', tag: ['support', 'robot'], place: 'close' },
  { name: "THRM-EX", rarity: 1, type: 'specialist', tag: ['nuker', 'robot', 'control'], place: 'close' },
  { name: "夜刀", rarity: 2, type: 'vanguard', tag: [], place: 'close' },
  { name: "黑角", rarity: 2, type: 'defender', tag: ['dps'], place: 'close' },
  { name: "芬", rarity: 3, type: 'vanguard', tag: [, 'recovery'], place: 'close' },
  { name: "翎羽", rarity: 3, type: 'vanguard', tag: [, 'dps', 'recovery'], place: 'close' },
  { name: "香草", rarity: 3, type: 'vanguard', tag: [, 'recovery'], place: 'close' },
  { name: "玫兰莎", rarity: 3, type: 'guard', tag: [, 'dps', 'survival'], place: 'close' },
  { name: "泡普卡", rarity: 3, type: 'guard', tag: [, 'survival'], place: 'close' },
  { name: "月见夜", rarity: 3, type: 'guard', tag: [, 'dps'], place: 'close' },
  { name: "斑点", rarity: 3, type: 'defender', tag: [, 'healing', 'defense'], place: 'close' },
  { name: "米格鲁", rarity: 3, type: 'defender', tag: [, 'defense'], place: 'close' },
  { name: "红豆", rarity: 4, type: 'vanguard', tag: [, 'dps', 'recovery'], place: 'close' },
  { name: "清道夫", rarity: 4, type: 'vanguard', tag: [, 'dps', 'recovery'], place: 'close' },
  { name: "桃金娘", rarity: 4, type: 'vanguard', tag: [, 'healing', 'recovery'], place: 'close' },
  { name: "艾丝黛尔", rarity: 4, type: 'guard', tag: [, 'survival'], place: 'close' },
  { name: "缠丸", rarity: 4, type: 'guard', tag: [, 'dps', 'survival'], place: 'close' },
  { name: "杜宾", rarity: 4, type: 'guard', tag: [, 'support', 'dps'], place: 'close' },
  { name: "刻刀", rarity: 4, type: 'guard', tag: [, 'dps', 'control'], place: 'close' },
  { name: "猎蜂", rarity: 4, type: 'guard', tag: [, 'dps'], place: 'close' },
  { name: "慕斯", rarity: 4, type: 'guard', tag: [, 'dps'], place: 'close' },
  { name: "霜叶", rarity: 4, type: 'guard', tag: [, 'dps', 'aoe'], place: 'close' },
  { name: "宴", rarity: 4, type: 'guard', tag: [, 'dps', 'survival'], place: 'close' },
  { name: "古米", rarity: 4, type: 'defender', tag: [, 'healing', 'defense'], place: 'close' },
  { name: "角峰", rarity: 4, type: 'defender', tag: [, 'defense'], place: 'close' },
  { name: "蛇屠箱", rarity: 4, type: 'defender', tag: [, 'defense'], place: 'close' },
  { name: "阿消", rarity: 4, type: 'specialist', tag: [, 'shift'], place: 'close' },
  { name: "暗索", rarity: 4, type: 'specialist', tag: [, 'shift'], place: 'close' },
  { name: "砾", rarity: 4, type: 'specialist', tag: [, 'defense', 'redeploy'], place: 'close' },
  { name: "德克萨斯", rarity: 5, type: 'vanguard', tag: ['recovery'], place: 'close' },
  { name: "极境", rarity: 5, type: 'vanguard', tag: ['support', 'recovery'], place: 'close' },
  { name: "凛冬", rarity: 5, type: 'vanguard', tag: ['support', 'recovery'], place: 'close' },
  { name: "苇草", rarity: 5, type: 'vanguard', tag: ['dps', 'recovery'], place: 'close' },
  { name: "布洛卡", rarity: 5, type: 'guard', tag: ['aoe', 'survival'], place: 'close' },
  { name: "诗怀雅", rarity: 5, type: 'guard', tag: ['support', 'dps'], place: 'close' },
  { name: "星极", rarity: 5, type: 'guard', tag: ['dps', 'defense'], place: 'close' },
  { name: "因陀罗", rarity: 5, type: 'guard', tag: ['dps', 'survival'], place: 'close' },
  { name: "幽灵鲨", rarity: 5, type: 'guard', tag: ['aoe', 'survival'], place: 'close' },
  { name: "白金", rarity: 5, type: 'sniper', tag: ['dps'], place: 'far' },
  { name: "灰喉", rarity: 5, type: 'sniper', tag: ['dps'], place: 'far' },
  { name: "蓝毒", rarity: 5, type: 'sniper', tag: ['dps'], place: 'far' },
  { name: "普罗旺斯", rarity: 5, type: 'sniper', tag: ['dps'], place: 'far' },
  { name: "慑砂", rarity: 5, type: 'sniper', tag: ['aoe', 'debuff'], place: 'far' },
  { name: "守林人", rarity: 5, type: 'sniper', tag: ['dps', 'nuker'], place: 'far' },
  { name: "送葬人", rarity: 5, type: 'sniper', tag: ['aoe'], place: 'far' },
  { name: "陨星", rarity: 5, type: 'sniper', tag: ['aoe', 'debuff'], place: 'far' },
  { name: "吽", rarity: 5, type: 'defender', tag: ['healing', 'defense'], place: 'far' },
  { name: "火神", rarity: 5, type: 'defender', tag: ['dps', 'survival', 'defense'], place: 'far' },
  { name: "可颂", rarity: 5, type: 'defender', tag: ['defense', 'shift'], place: 'far' },
  { name: "雷蛇", rarity: 5, type: 'defender', tag: ['dps', 'defense'], place: 'far' },
  { name: "临光", rarity: 5, type: 'defender', tag: ['healing', 'defense'], place: 'far' },
  { name: "石棉", rarity: 5, type: 'defender', tag: ['dps', 'defense'], place: 'far' },
  { name: "白面鸮", rarity: 5, type: 'supporter', tag: ['healing', 'support'], place: 'far' },
  { name: "赫默", rarity: 5, type: 'supporter', tag: ['healing'], place: 'far' },
  { name: "华法琳", rarity: 5, type: 'supporter', tag: ['healing', 'support'], place: 'far' },
  { name: "初雪", rarity: 5, type: 'supporter', tag: ['debuff'], place: 'far' },
  { name: "格劳克斯", rarity: 5, type: 'supporter', tag: ['slow',], place: 'far' },
  { name: "梅尔", rarity: 5, type: 'supporter', tag: ['dps', 'slow', 'summon', 'dps', 'aoe'], place: 'far' },
  { name: "巫恋", rarity: 5, type: 'supporter', tag: ['debuff'], place: 'far' },
  { name: "月禾", rarity: 5, type: 'supporter', tag: ['support', 'survival'], place: 'far' },
  { name: "真理", rarity: 5, type: 'supporter', tag: ['dps', 'slow'], place: 'close' },
  { name: "惊蛰", rarity: 5, type: 'caster', tag: ['dps'], place: 'close' },
  { name: "夜魔", rarity: 5, type: 'caster', tag: ['healing', 'dps', 'slow'], place: 'close' },
  { name: "红", rarity: 5, type: 'specialist', tag: ['redeploy'], place: 'close' },
  { name: "槐琥", rarity: 5, type: 'specialist', tag: ['debuff', 'redeploy'], place: 'close' },
  { name: "狮蝎", rarity: 5, type: 'specialist', tag: ['dps', 'survival'], place: 'close' },
  { name: "食铁兽", rarity: 5, type: 'specialist', tag: ['slow', 'shift'], place: 'close' },
  { name: "崖心", rarity: 5, type: 'specialist', tag: ['dps', 'shift'], place: 'close' },
  { name: "风笛", rarity: 6, type: 'vanguard', tag: ['dps', 'recovery'], place: 'close' },
  { name: "推进之王", rarity: 6, type: 'vanguard', tag: ['dps', 'recovery'], place: 'close' },
  { name: "陈", rarity: 6, type: 'guard', tag: ['dps', 'nuker'], place: 'close' },
  { name: "赫拉格", rarity: 6, type: 'guard', tag: ['dps', 'survival'], place: 'close' },
  { name: "煌", rarity: 6, type: 'guard', tag: ['dps', 'survival'], place: 'close' },
  { name: "斯卡蒂", rarity: 6, type: 'guard', tag: ['dps', 'survival'], place: 'close' },
  { name: "银灰", rarity: 6, type: 'guard', tag: ['support', 'dps'], place: 'close' },
  { name: "塞雷娅", rarity: 6, type: 'defender', tag: ['healing', 'support', 'defense'], place: 'close' },
  { name: "星熊", rarity: 6, type: 'defender', tag: ['dps', 'defense'], place: 'close' },
  { name: "傀影", rarity: 6, type: 'specialist', tag: ['dps', , 'redeploy'], place: 'close' },
  { name: "温蒂", rarity: 6, type: 'specialist', tag: ['dps', 'shift',], place: 'close' },
  { name: "正义骑士号", rarity: 1, type: 'sniper', tag: ['support', 'robot'], place: 'far' },
  { name: "Lancet-2", rarity: 1, type: 'supporter', tag: ['healing', 'robot'], place: 'far' },
  { name: "巡林者", rarity: 2, type: 'sniper', tag: [], place: 'far' },
  { name: "12F", rarity: 2, type: 'caster', tag: [], place: 'far' },
  { name: "杜林", rarity: 2, type: 'caster', tag: [], place: 'far' },
  { name: "安德切尔", rarity: 3, type: 'sniper', tag: [, 'dps'], place: 'far' },
  { name: "克洛丝", rarity: 3, type: 'sniper', tag: [, 'dps'], place: 'far' },
  { name: "空爆", rarity: 3, type: 'sniper', tag: [], place: 'far' },
  { name: "安赛尔", rarity: 3, type: 'medic', tag: [, 'healing'], place: 'far' },
  { name: "芙蓉", rarity: 3, type: 'medic', tag: [, 'healing'], place: 'far' },
  { name: "梓兰", rarity: 3, type: 'supporter', tag: [, 'aoe'], place: 'far' },
  { name: "史都华德", rarity: 3, type: 'caster', tag: [, 'dps'], place: 'far' },
  { name: "炎熔", rarity: 3, type: 'caster', tag: [], place: 'far' },
  { name: "安比尔", rarity: 4, type: 'sniper', tag: [, 'dps', 'aoe'], place: 'far' },
  { name: "白雪", rarity: 4, type: 'sniper', tag: [, 'aoe'], place: 'far' },
  { name: "红云", rarity: 4, type: 'sniper', tag: [, 'dps'], place: 'far' },
  { name: "杰西卡", rarity: 4, type: 'sniper', tag: [, 'dps', 'survival'], place: 'far' },
  { name: "流星", rarity: 4, type: 'sniper', tag: [, 'dps', 'debuff'], place: 'far' },
  { name: "梅", rarity: 4, type: 'sniper', tag: [, 'dps', 'aoe'], place: 'far' },
  { name: "调香师", rarity: 4, type: 'medic', tag: [, 'healing'], place: 'far' },
  { name: "末药", rarity: 4, type: 'medic', tag: [, 'healing'], place: 'far' },
  { name: "清流", rarity: 4, type: 'medic', tag: [, 'healing', 'support'], place: 'far' },
  { name: "苏苏洛", rarity: 4, type: 'medic', tag: [, 'healing'], place: 'far' },
  { name: "地灵", rarity: 4, type: 'supporter', tag: [, 'aoe'], place: 'far' },
  { name: "格雷伊", rarity: 4, type: 'caster', tag: [, 'aoe'], place: 'far' },
  { name: "夜烟", rarity: 4, type: 'caster', tag: [, 'dps', 'debuff'], place: 'far' },
  { name: "远山", rarity: 4, type: 'caster', tag: [], place: 'far' },
  { name: "黑", rarity: 6, type: 'sniper', tag: ['dps'], place: 'far' },
  { name: "能天使", rarity: 6, type: 'sniper', tag: ['dps'], place: 'far' },
  { name: "闪灵", rarity: 6, type: 'medic', tag: ['healing', 'support'], place: 'far' },
  { name: "夜莺", rarity: 6, type: 'medic', tag: ['healing', 'support'], place: 'far' },
  { name: "麦哲伦", rarity: 6, type: 'supporter', tag: ['support', 'dps', 'slow'], place: 'far' },
  { name: "刻俄柏", rarity: 6, type: 'caster', tag: ['dps',], place: 'far' },
  { name: "莫斯提马", rarity: 6, type: 'caster', tag: ['support', 'aoe',], place: 'far' },
  { name: "伊芙利特", rarity: 6, type: 'caster', tag: ['aoe', 'debuff'], place: 'far' },
  { name: "阿", rarity: 6, type: 'specialist', tag: ['support', 'dps'], place: 'far' },
]